### PR TITLE
feat(peft): add llama token classification example

### PR DESCRIPTION
**Pull request by SauravMaheshkar**
Adds notebook for Token Classification example for [**Fine-tuning llama 2 for Named Entity Recognition**](https://wandb.ai/sauravmaheshkar/Llama-NER/reports/Fine-tuning-llama-2-for-Named-Entity-Recognition--Vmlldzo3ODk2NDc3).

* I also created a `peft/` directory since there are other notebooks related to other articles hosted on my gists that should live on `wandb/examples`.

Request for Review: @tcapelle @soumik12345

### CODE REVIEW

**Comment by tcapelle** [comment]
Hey, can you just use 
```
import wandb
wandb.login()
```
instead?

**Comment by SauravMaheshkar** [comment]
> Hey, can you just use
> 
> ```
> import wandb
> wandb.login()
> ```
> 
> instead?

Addressed in [2fe5f12](https://github.com/wandb/examples/pull/525/commits/2fe5f1222cf946d15a7de7a3a007b2a0a25ba60e)

**Comment by tcapelle** [comment]
Two extra small changes:
- remove the entity = "saurav" and default to None (so it' uses your default entity after calling `wandb.login`)
- Add the image to the peft folder and import it as a static image on the notebook (``.

**Comment by tcapelle** [comment]
extra detail, use a relative path to the image, so when we merge the path to your branch is not needed

**Comment by SauravMaheshkar** [comment]
> extra detail, use a relative path to the image, so when we merge the path to your branch is not needed

The image is not in my fork of the `wandb/examples` repository but rather in my `SauravMaheshkar/SauravMaheshkar` repository.

**Comment by tcapelle** [comment]
add it to the folder then

**Pull request merged**
