### PR TITLE
Weights & Biases integration with MONAI

### PR DESCRIPTION
**Pull request by Gladiator07**
This notebook is for the [report](https://wandb.ai/gladiator/MONAI_Spleen_3D_Segmentation/reports/3D-Segmentation-with-MONAI-and-PyTorch-supercharged-by-Weights-Biases---VmlldzoyNDgxNDMz) demonstrating W&B integration with MONAI.

### CODE REVIEW

**Comment by morganmcg1** [comment]
Thanks for the PR @Gladiator07 ! Can you strip all of the output from the notebook please? Its makes the notebook super long right now 🙏

**Comment by Gladiator07** [comment]
Hi @morganmcg1 , I removed the cell outputs from the notebook.

**Comment by morganmcg1** [comment]
@Gladiator07 could you copy the first 2 cells from https://wandb.me/intro and use them (feel free to rename of course). I think the test is failing because we check for specific code in those 2 cells. Thanks!

**Comment by Gladiator07** [comment]
@morganmcg1 added colab link and W&B logo to first two cells. Thanks!

**Comment by morganmcg1** [comment]
thanks @Gladiator07 , looks good to me!

**Pull request merged**
