### PR TITLE
Demo of Paella with Weights & Biases

### PR DESCRIPTION
**Pull request by soumik12345**

### CODE REVIEW

**Review by tcapelle — COMMENTED** [review]
don't hardcode your user as entity

**Review by tcapelle — COMMENTED** [review]
Don't hard code your user as entity

**Review by tcapelle — COMMENTED** [review]
Does the notebooks run in colab?

**Comment by soumik12345** [comment]
> Does the notebooks run in colab?

@tcapelle It runs on colab, but only with the premium GPU.

**Review by tcapelle — APPROVED** [review]

**Pull request merged**
