### PR TITLE
Add ray tune example

### PR DESCRIPTION
**Pull request by AyushExel**
Things to note:

- Make sure that `os.environ['WANDB_API_KEY']` is set. Ray tune requires you to manually pass API key or API Key file path if it cannot find `WANDB_API_KEY` environment variable. So, as this example will be used for testing, I have omitted the part that manually asks the user to input the api_key and have assumed that `WANDB_API_KEY` is set.

- This example uses a hardcoded wandb `project` name because ray tune requires a project name when using `WandbLogger` otherwise it throws an error.

### CODE REVIEW

**Comment by charlesfrye** [comment]
fyi @AyushExel im trying to get this example incorporated into our regression testing before approving this PR.

are you positive that you need an API key? what about anonymous mode? @raubitsj might be able to help here.

@AyushExel some things you can do in the interim are
- drop numpy from the requirements, since it's not really used
- remove the blank lines 13 and 14
- remove the components that ensure determinism. it's not really relevant here.
- ensure there are two blank lines before the @wandb_mixin decorator (here there's just 1)
- remove the commented api_key line
- add a `return` to `train_mnist`
- ensure there's one blank line between the end of the definition of `train_mnist` and the next line of code (currently there are two)
- line up `resources_per_trial` and `config` with the other arguments 
- change line 54 to `"wandb": { "project": "ray-example"},` (whitespace, mixed `"` and `'`)
- remove extra newlines inside tune.run call (`50`, `55`)
- drop the print statement

this would be a good file to practice using `flake8` (or a similar tool) on!

**Comment by AyushExel** [comment]
Thanks, @charlesfrye for the review. I didn't know examples were supposed to pass the flake8 test like the wand/client repo is supposed to. I have made some edits and now the code passes flake8 test.
To answer your questions:
- Yes the way the integration is designed, it checks for API key, API key file or environment variable and throws an error if not found. I haven't looked in their repo yet so there might be a workaround that I'm not aware of.

About adding a `return` statement at the end of `train_mnist`, I'm not sure what that would accomplish. Adding a blank `return` statement will return `None` and a function without a `return` statement also returns `None`

**Comment by raubitsj** [comment]
> Things to note:
> 
> * Make sure that `os.environ['WANDB_API_KEY']` is set. Ray tune requires you to manually pass API key or API Key file path if it cannot find `WANDB_API_KEY` environment variable. So, as this example will be used for testing, I have omitted the part that manually asks the user to input the api_key and have assumed that `WANDB_API_KEY` is set.

1) Add comment and/or assertion about api key
Please add a note in the code that says this.  I will fix this with a better way later.

> * This example uses a hardcoded wandb `project` name because ray tune requires a project name when using `WandbLogger` otherwise it throws an error.

2) add argparse for setting project
Argh, ok, i will look at their integration and submit a PR later to fix this also.   You might want to at least use argparse to set this project so it isnt fully hardcoded.

3) add requirements.txt to this directory

**Comment by charlesfrye** [comment]
@AyushExel though the examples don't currently have PEP8-formatting, we should avoid introducing more unformatted code.

You're right about the `return` statement! I always assumed that including a return was part of PEP8, but I guess that's just my personal style.

Thanks for the clarification with the API key. Seems like Jeff has a plan for fixing this in the future.

**Review by charlesfrye — CHANGES_REQUESTED** [review]
You can remove Lines 12-15 (plus their whitespace). It doesn't matter so much if this example is deterministic, since there are no outputs being captured.

Bare minimum, the strings being hashed need to be changed because they no longer read as a correct sentence: "setting random seeds by removing stochasticity" is incorrect. I think it's easier to drop them.

Line 46 should be `"wandb": {"project": "ray-example"},`, with a space after the colon.

I'm not convinced you need the print statement on Line 52 (esp since it reveals API keys).

**Comment by raubitsj** [comment]
looks good.  @charlesfrye are you ok with this? i would love to get this in the regression this week

**Comment by charlesfrye** [comment]
LGTM!

**Review by charlesfrye — APPROVED** [review]

**Comment by raubitsj** [comment]
FYI: I added the regression test for this:
https://github.com/wandb/wandb-testing/commit/a768fb2bf098734be4c85c811c3df8b4fd028d25

**Pull request merged**
