### PR TITLE
update pytorch_lightning example

### PR DESCRIPTION
**Pull request by rohitgr7**
Updated the lightning example as per the recent release.

I would like to update the examples here too:
- https://wandb.me/lightning
- https://docs.wandb.ai/guides/integrations/lightning

Can you point me to the files I need to update?

### CODE REVIEW

**Comment by rohitgr7** [comment]
cc @scottire

**Comment by tcapelle** [comment]
Thanks for the interest!

Ok, I added @borisdayma  notebooks on lightning [here](https://github.com/wandb/examples/blob/master/colabs/pytorch-lightning/Optimize_Pytorch_Lightning_models_with_Weights_%26_Biases.ipynb) so you can propose fixes. Can you tell me where did you found this notebooks link ?

**Comment by rohitgr7** [comment]
thanks @tcapelle for the reference. I'll make changes for the colab notebook as you suggested.
btw you can redirect the link for [wandb.me/lightning](https://wandb.me/lightning) to [colab.research.google.com/github/wandb/examples/blob/master/colabs/pytorch-lightning/Optimize_Pytorch_Lightning_models_with_Weights_%26_Biases.ipynb](https://colab.research.google.com/github/wandb/examples/blob/master/colabs/pytorch-lightning/Optimize_Pytorch_Lightning_models_with_Weights_%26_Biases.ipynb) so that it won't require a manual upload.

thanks @scottire for reaching out. I'll share the updated docs with you.

**Comment by borisdayma** [comment]
Nice, can you keep me in the loop?
I had started updating the docs to add examples of the new media support but didn't finish.

**Comment by rohitgr7** [comment]
sure!

**Comment by borisdayma** [comment]
Just for info, the guide at wandb.me/lightning is updated with the media logging.
It's being reviewed and I'm going to add it somewhere so you can contribute to it as well.

**Comment by rohitgr7** [comment]
thanks, @borisdayma . I'll make a PR with the updates once your's get merged.

**Comment by borisdayma** [comment]
For info this is the PR: https://github.com/wandb/examples/pull/107

**Pull request merged**
