### PR TITLE
Simple Training loop in JAX and Flax

### PR DESCRIPTION
**Pull request by soumik12345**
## Notebooks

- [x] Simple Training loop in JAX and Flax
- [x] Creating TFRecord files
- [x] Training using TFRecords
- [x] Add markdown cells containing explanations

Colab with @SauravMaheshkar

### CODE REVIEW

**Comment by tcapelle** [comment]
It looks awesome!
Would you mind adding some markdown cells with descriptions of what you are doing?

**Comment by SauravMaheshkar** [comment]
@tcapelle I just annotated the first notebook in [6266288](https://github.com/wandb/examples/pull/275/commits/62662889ab625860e1e35f1ae97d788c467202cd). LMK if it looks fine or should I add more markdown cells.

**Comment by tcapelle** [comment]
thanks, this is very cool.

**Comment by tcapelle** [comment]
I will do some clean up ad merge

**Pull request merged**
