### PR TITLE
PyTorch Example to Generate Faces using DCGANs

### PR DESCRIPTION
**Pull request by ishandutta0098**
## About the PR
Added an example notebook to Generate faces using DCGANs in PyTorch. A report for this is also available on the dashboard.

[Colab Link](https://colab.research.google.com/drive/1Bd0nbAmcA5QhgaOCpciqc55ftqTAP9JO?usp=sharing)
[Wandb Dashboard](https://wandb.ai/ishandutta/W&B_Generate_Faces_using_DCGAN?workspace=user-ishandutta) 

## Requesting Review
@soumik12345 @tcapelle

### CODE REVIEW

**Review by soumik12345 — CHANGES_REQUESTED** [review]
Hi @ishandutta0098, I added my initial review which you can refer to in the ReviewNB comments in this thread. Please make these changes.

**Comment by ishandutta0098** [comment]
Hi, @soumik12345 I am checking them and will update you soon.

**Comment by tcapelle** [comment]
<p>👍</p>

---

 <a href='https://app.reviewnb.com/wandb/examples/pull/350/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tcapelle** [comment]
<p>My newest trick is <code>from tqdm.auto import tqdm</code></p>

---

 <a href='https://app.reviewnb.com/wandb/examples/pull/350/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ishandutta0098** [comment]
Hi @soumik12345, as discussed I am closing this PR until further confirmation on the type of examples that can be contributed to the repository.

**Pull request closed without merging**
