### PR TITLE
update parameter name for sweep batch distribution.

### PR DESCRIPTION
**Pull request by jemiahlee**
I got an ~error~ warning when running this this morning that seems to be cleared when updating to this new value.

### CODE REVIEW

**Comment by tcapelle** [comment]
good catch!

**Comment by tcapelle** [comment]
For me this notebook runs fine in colab. Can you post the error?

**Comment by jemiahlee** [comment]
Screen Shot 2022-04-06 at 2 25 23 PM

**Comment by jemiahlee** [comment]
The screenshot was captured on a brand new run, so I was able to repro the issue; not sure whether this is strictly necessary, but running the prompts one at a time, this seemed disconcerting as a new user.

**Comment by tcapelle** [comment]
Can you post the sweep config dict before running the sweep?

**Pull request merged**
