### PR TITLE
Simple Automations demo project

### PR DESCRIPTION
**Pull request by cvphelps**
This quick tutorial shows users how to train and test a model using automations with W&B.

### CODE REVIEW

**Comment by ngrayluna** [comment]
Some thoughts: 

* Training script takes ~10 minutes to run. Not a blocker, but would be nice if we had a shorter training script.
* In W&B Report, I would call out installing the requirements.txt right after we tell them to clone it.
* Order of operations is key. I confused myself for a minute with whether or not I needed to launch the job before making an automation (like people are normally accustomed to).
* Might be good to call out that queues are entity scoped. So when I tried to run it on my queue w/ my entity it didn't work.
* Not sure if this is expected behavior, or if I am doing it wrong, but the automation page is blank, even when I create an automation?

**Review by ngrayluna — APPROVED** [review]

**Comment by cvphelps** [comment]
Thank you Noah!

**Comment by cvphelps** [comment]
1. **Training script time**: I'm updating the train.py to have a `train_set` config param that is set by default to 2560. This means there will only be 20 steps of training instead of 470.

**Comment by cvphelps** [comment]
**requirements.txt**: Done, I've updated the report 
image

**Comment by cvphelps** [comment]
Confirming new training script runs in less than 30s 
image

**Comment by cvphelps** [comment]
I'm adding logging to get the requirements.txt file since I turned off github repo logging so I could name the job a custom name

**Pull request merged**
