### PR TITLE
Adds Intro colab; fixes whitespace and .finish

### PR DESCRIPTION
**Pull request by charlesfrye**
This branch demonstrates the process for adding Colabs outlined in #28.

Additionally, it makes the following changes to the Colab:

1. Unifies whitespace style: 4 spaces, instead of mixed 4 and 2.
2. Adds `%%capture`s to the installation cells. This is of debatable utility, since the notebook uses the private outputs feature, but I wanted to demonstrate it.
3. Adds `.finish` in between the two `.init` calls.
4. Adds a few comments.

@ayulockin, take a look.

### CODE REVIEW

**Comment by vanpelt** [comment]
I setup reviewnb incase it's useful: https://app.reviewnb.com/wandb/examples

**Comment by vanpelt** [comment]
Not really sure how it's supposed to work.  The fastai folks use it a lot, here's this file: https://app.reviewnb.com/wandb/examples/blob/cf%2Fadd-intro-colab/colabs%2Fintro%2FIntro_to_Weights_%26_Biases.ipynb/file

**Comment by charlesfrye** [comment]
That is very useful, thanks @vanpelt! Unfortunately since the Colabs originated off VC, we can't see the diff, but this will be very helpful moving forward.

**Comment by ayulockin** [comment]
This is helpful. 

The updates made in the colab looks good. However, I am not the author of this colab notebook and hence this [pointer](https://github.com/wandb/examples/issues/28#issuecomment-697441932). I guess Carey is the author of this notebook.

**Pull request merged**
